### PR TITLE
Add strict mode to strictly match hex tokens

### PR DESCRIPTION
**Pull request by btholt**
Went ahead and did it.
- Added strict mode
- Updated README.md to reflect the addition
- Bumped version to 1.1.0 (happy to take that out; just seemed like the right thing to do)
- Added tests to cover the new functionality

### CODE REVIEW

**Comment by btholt** [comment]
Cool. I'll amend my commit so the version number is 1.0.2 here in a bit. I'll leave the restyling of the README to you. :smile:

**Comment by tunnckoCore** [comment]
@btholt sorry for the delay, i come to it... lol. I'll try to push it up today.

**Comment by tunnckoCore** [comment]
@btholt hm... is that should return false? 

``` js
hexColorRegex().test('#123fff}')
//=> true, now
```

/cc @regexps/owners

**Comment by tunnckoCore** [comment]
@btholt published as `npm@v1.0.2` cuz there's no breaking change

**Comment by btholt** [comment]
Hooray! Thank you!

**Comment by tunnckoCore** [comment]
Yea, sorry for the long delay. :beer:

**Comment by btholt** [comment]
No apology necessary. I'm hugely appreciative. :tada:

**Pull request merged**
